name: Docker Image CI

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jonasfranke/cdn:latest
            ghcr.io/jonasfranke/cdn:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (no master)
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jonasfranke/cdn:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

